# Generated by Django 4.2.3 on 2023-07-13 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_1', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['create_at']},
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='created_at',
            new_name='create_at',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='updated_at',
            new_name='update_at',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='created_at',
            new_name='create_at',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='updated_at',
            new_name='update_at',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='body',
        ),
        migrations.AddField(
            model_name='comment',
            name='comment',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='post',
            name='body',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
